### ISSUE TITLE
About CVE-2020-36197 pre-auth

### ISSUE THREAD

**Issue by achuna33** [ShielderSec/poc#1]
The vulnerability information shows that authentication is required but it is not displayed in the poc，why？

**Comment by polict** [comment]
Hi @achuna33,

[CVE-2020-36197](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36197) doesn't require authentication in order to be exploited. You can find more info about that at this specific paragraph https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#pre-auth-arbitrary-file-write-in-musicstation

[CVE-2020-36198](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36198) instead does require "local access" (basically the privilege to write a file in a specific folder, more info at this paragraph https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#command-injection-in-malwareremover), but in this case that's gained from exploiting CVE-2020-36197 mentioned above. 

All in all neither of the vulnerabilities require any sort of authentication and the exploit spawns a remote root shell without any credential needed.

Let me know if you have further questions and I'll reopen this

**Comment by achuna33** [comment]
I have performed package verification for some targets, and have successfully returned the long pass path, but there is no URLDNS log

**Comment by achuna33** [comment]
I have performed package verification for some targets, and have successfully returned to the upload path, but after a day of waiting, there is no URLDNS log

**Comment by achuna33** [comment]
> 嗨@achuna33，
> 
> [CVE-2020-36197](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36197)不需要身份验证即可被利用。您可以在此特定段落中找到有关此内容的更多信息[https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#pre-auth-arbitrary-file-write-音乐台内](https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#pre-auth-arbitrary-file-write-in-musicstation)
> 
> [CVE-2020-36198](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36198)确实需要“本地访问”（基本上是在特定文件夹中写入文件的权限，本段中的更多信息[https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre- auth-remote-code-execution/#command-injection-in-malwareremover](https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#command-injection-in-malwareremover)），但在这种情况下，这是通过利用上述 CVE-2020-36197 获得的。
> 
> 总而言之，这两个漏洞都不需要任何类型的身份验证，并且该漏洞利用会生成一个远程 root shell，而无需任何凭据。
> 
> 如果您有其他问题，请告诉我，我将重新打开此问题

I have performed package verification for some targets, and have successfully returned to the upload path, but after a day of waiting, there is no URLDNS log

**Comment by achuna33** [comment]
> > 嗨@achuna33，
> > [CVE-2020-36197](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36197)您[无需](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36197)身份验证就被利用了。您在此特定段落中找到有关此内容的更多信息[https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth -remote-code-execution/#pre-auth-arbitrary-file-write-音乐台内](https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#pre-auth-arbitrary-file-write-in-musicstation)
> > [CVE-2020-36198](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36198)确实需要“本地访问”（原来是在特定部分中写入文件的权限，本机中的更多信息[https://www.shielder.it/advisories/qnap-musicstation-malwareremover -pre- auth-remote-code-execution/#command-injection-in-malwareremover](https://www.shielder.it/advisories/qnap-musicstation-malwareremover-pre-auth-remote-code-execution/#command-injection-in-malwareremover)），但在这种情况下，这是通过利用上述 CVE-2020-36197 获得的。
> > 这两个漏洞都不需要任何类型的身份验证，该漏洞利用会生成一个 root shell，并且不会任何总远程。
> > 如果您有其他问题，请告诉我，我将重新打开这个问题
> 
> 我对一些target进行了包验证，成功返回上传路径，但是等了一天，没有URLDNS日志

MalwareRemover may not be installed on the target machine. Do you know any way to solve this problem? How can I make my program successful?

**Comment by polict** [comment]
If MalwareRemover is not installed on the target machine you need to find another file write -> rce gadget in your specific context, but I'll not be able to further help you with that. Please open a new issue if you have new questions regarding our PoCs.
